name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Configure Docker credential helper
        env:
          GOVANITYURLS_SERVICE_ACCOUNT_JSON_KEY: ${{ secrets.GOVANITYURLS_SERVICE_ACCOUNT_JSON_KEY }}
        run: |
          echo "install gcloud cli"
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get -qq update
          sudo apt-get install -y google-cloud-sdk google-cloud-sdk-app-engine-go
          echo
          echo "configure gcloud auth"
          echo "$GOVANITYURLS_SERVICE_ACCOUNT_JSON_KEY" > "$HOME"/gcp.json
          gcloud auth activate-service-account --key-file=$HOME/gcp.json

      - name: Deploy
        run: gcloud app deploy --project voyagermesh-dev
